- name: Add custom parameter at the end of sysctl.conf based on group_vars
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    line: "{{ item }}"
  with_items:
    - "{{ kernel_config }}"

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Add custom parameter at the end of limits.conf based on group_vars
  ansible.builtin.lineinfile:
    path: "/etc/security/limits.conf"
    line: "{{ item }}"
  with_items:
    - "{{ limits_config }}"

- name: Update specific lines in /etc/default/grub
  block:
    - name: Configure RUB_CMDLINE_LINUX_DEFAULT parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: '{{ grub_cmdline }}'
        mode: "0644"

    - name: Configure GRUB_CMDLINE_LINUX parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX='
        line: '{{ grub_cmdline_2 }}'
        mode: "0644"

- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  changed_when: true

- name: Disable Transparent Huge Pages
  ansible.builtin.shell: |
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    echo never > /sys/kernel/mm/transparent_hugepage/defrag
  changed_when: true

- name: Refresh swap settings
  ansible.builtin.shell: swapoff -a && swapon -a
  changed_when: true
