- name: Update specific lines in nebula-graphd.conf
  block:
    - name: Configure meta_server_addrs parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
        regexp: '^--meta_server_addrs='
        line: "--meta_server_addrs={{ nebula_meta_server_addrs }}"
        create: false

    - name: Configure local_ip parameter based on host IP
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
        regexp: '^--local_ip='
        line: "--local_ip={{ ansible_host }}"

    - name: Configure enable_authorize parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
        regexp: '^--enable_authorize='
        line: "{{ nebula_auth }}"
        create: false

    - name: Configure max_job_size parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
        regexp: '^--max_job_size='
        line: "{{ nebula_maxjobsize }}"
        create: false

    - name: Configure listen_backlog parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
        regexp: '^--listen_backlog='
        line: "{{ nebula_listen_backlog }}"

- name: Add custom parameter at the end of nebula-graphd.conf
  ansible.builtin.blockinfile:
    path: "{{ nebula_install_path }}/etc/nebula-graphd.conf"
    block: |
      {{ nebula_heartbeat }}
      --timezone_name={{ nebula_timezone }}
    create: false
    marker: "# {mark} CUSTOM CONFIGURATION"


- name: Update specific lines in nebula-metad.conf
  block:
    - name: Configure meta_server_addrs parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-metad.conf"
        regexp: '^--meta_server_addrs='
        line: "--meta_server_addrs={{ nebula_meta_server_addrs }}"
        create: false

    - name: Configure local_ip parameter based on host IP
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-metad.conf"
        regexp: '^--local_ip='
        line: "--local_ip={{ ansible_host }}"
        create: false

    - name: Configure data_path parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-metad.conf"
        regexp: '^--data_path='
        line: "{{ metad_datapath }}"
        create: false

    - name: Configure heartbeat_interval_secs parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-metad.conf"
        regexp: '^--heartbeat_interval_secs='
        line: "{{ nebula_heartbeat }}"
        create: false

- name: Add custom parameter at the end of nebula-metad.conf
  ansible.builtin.blockinfile:
    path: "{{ nebula_install_path }}/etc/nebula-metad.conf"
    block: |
      --timezone_name={{ nebula_timezone }}
    create: false
    marker: "# {mark} CUSTOM CONFIGURATION"

- name: Update specific lines in nebula-storaged.conf
  block:
    - name: Configure meta_server_addrs parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-storaged.conf"
        regexp: '^--meta_server_addrs='
        line: "--meta_server_addrs={{ nebula_meta_server_addrs }}"
        create: false

    - name: Configure local_ip parameter based on host IP
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-storaged.conf"
        regexp: '^--local_ip='
        line: "--local_ip={{ ansible_host }}"
        create: false

    - name: Configure data_path parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-storaged.conf"
        regexp: '^--data_path='
        line: "{{ storaged_datapath }}"
        create: false

    - name: Configure heartbeat_interval_secs parameter based on group_vars
      ansible.builtin.lineinfile:
        path: "{{ nebula_install_path }}/etc/nebula-storaged.conf"
        regexp: '^--heartbeat_interval_secs='
        line: "{{ nebula_heartbeat }}"
        create: false

- name: Add custom parameter at the end of nebula-storaged.conf
  ansible.builtin.blockinfile:
    path: "{{ nebula_install_path }}/etc/nebula-storaged.conf"
    block: |
      --timezone_name={{ nebula_timezone }}
    create: false
    marker: "# {mark} CUSTOM CONFIGURATION"
