- name: Start Nebula Graph
  ansible.builtin.command: "/usr/local/nebula/scripts/nebula.service start all"
  become: true
  changed_when: true

- name: Check the status of the nebula service
  ansible.builtin.command: "/usr/local/nebula/scripts/nebula.service status all"
  become: true
  changed_when: true
  register: nebula_status

- name: Print the status of the nebula service
  ansible.builtin.debug:
    var: nebula_status.stdout

- name: Download Nebula Graph Console and Set permission
  ansible.builtin.get_url:
    url: "https://github.com/vesoft-inc/nebula-console/releases/download/v{{ nebula_version }}/nebula-console-linux-amd64-v{{ nebula_version }}"
    dest: '/opt/nebula/nebula-graph-console'
    mode: 'a+x'
